### ISSUE TITLE
Error trying to pass context via constructor

### ISSUE THREAD

**Issue by connorjburton** [mjancarik/shallow-with-context#3]
Hi,

Now we have changed the `createHook` function to run on all functions, we get an error when trying to call a function in the same class in the constructor. As it tries to pass context (that does not exist yet).

```js
class Foo extends React.Component {
    constructor() {
        this.doSomethng();
    }

    doSomething() {
        console.log('hello');
    }
}
```

Running a test for this with `createContext` and `withContext` returns the error

`TypeError: Cannot convert undefined or null to object at hasOwnProperty`

This is because `shallowWithContext.cjs.js:18` doesn't check to see if context is an object or not, if you call a function in constructor `context` will be undefined, which then gets passed into `Object.prototype.hasOwnProperty`, which throws the error. A quick fix I made was change `const originalContext = context.context` to `const originalContext = context.context || {}` however I am not sure that is a good solution.

**Comment by mjancarik** [comment]
Hi,

Thanks for report. Your quick fix works but I added check if context is an object. I release shallow-with-context@0.2.1.

**Comment by connorjburton** [comment]
Thanks, works now!
