### ISSUE TITLE
createContext args

### ISSUE THREAD

**Issue by samklonaris** [mjancarik/shallow-with-context#5]
How does the `createContext` work?

If I call `createContext({key1: 'val1'})`  I would expect the context to be
```
{
    key1: 'val1'
}
```
(my components also expect this so that i can do `context.key`)

But instead it is 
```
{
   value: {
      key1: 'va;1'
   }
}
```

Is this expected behavior?  fwiw this is my first time using the context api, and I may have set something up incorrectly.

**Comment by mjancarik** [comment]
Hi,

Thanks for report. Could you send me all your test case snippet or example for creating fix.

The createContext method returns object similar to:

```javascript
//createContext({ key: 'context value' });
{
   value: {
       key: 'context value'
   },
   __SHALLOW_CONTEXT_FLAG__: true
}
```
It's need it for primitive values. Something like this:
```javascript
createContext('context value');
```
In your component you should use:
```javascript
render() {
    return <div>{this.context.key}</div>;
}
```

You can try [workaround](https://github.com/mjancarik/shallow-with-context/issues/2#issuecomment-572251141) than I fix it.

**Comment by samklonaris** [comment]
Thanks for the quick reply!

My use case:
```
export default class MyComponent extends React.Component {
     static contextType = MyContext;

     render() {
         const { type } = this.context;
         ....
         return (...)
    }
}

test('test 1', () => {
    const context = createContext( { type: 'user' });
    const MyComponentWithContext = withContext(MyComponent, context);

    const component = shallow(
      <MyComponentWithContext {...defaultProps} />,
      { context: context },
    );
    expect(component).toMatchSnapshot();
  });
```

The issue I am having is that in the component
```
this.context = {
   value: {
       type: 'user'
   },
   __SHALLOW_CONTEXT_FLAG__: true
}
```

But I need to access `this.context.type`.

The temp fix works.  thanks!

**Comment by mjancarik** [comment]
Hi,

I try your use case and everything works for me. Will you send me more informations about your test framework, node.js version and babel config?

**Comment by mjancarik** [comment]
I updated documentation and I am closing issue because I didn't simulate it.
